name: scmocha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - samtools
  - bcftools
  - pip
  - r-base
  - r-tidyverse
  - r-seurat
  - bioconductor-gmoviz
  - r-biocmanager
  - r-devtools
  - perl
  - perl-dbi
  - sqlite
  - perl-app-cpanminus
  - gxx_linux-64
  - pip:
    - flake8
    - black
    - sinto
